#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


TEST_DIR="`dirname "$0"`"
PROJECT_DIR="$( cd "${TEST_DIR}/.." ; pwd -P)"


main()
{
   _options_mini_main "$@" && set -x

   MULLE_SDE_EXTENSION_PATH="${PROJECT_DIR}/src:${MULLE_SDE_EXTENSION_PATH}"
   export MULLE_SDE_EXTENSION_PATH

   local i

   log_verbose "mulle-sde: `mulle-sde version` (`mulle-sde libexec-dir`)"

   OUTPUT_DEVICE=
   for i in "${TEST_DIR}"/*
   do
      if [ -x "$i/run-test" ]
      then
         log_verbose "------------------------------------------"
         log_info    "$i:"
         log_verbose "------------------------------------------"
         if [ "${MULLE_FLAG_LOG_TERSE}" = 'YES' ]
         then
            ( cd "$i" && ./run-test "$@" > /dev/null 2>&1 ) || fail "Test \"$i\" failed"
         else
            ( cd "$i" && ./run-test "$@" ) || fail "Test \"$i\" failed"
         fi
      fi
   done
}


main "$@"
