language: c

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:george-edison55/cmake-3.x'

    packages:
      - cmake
      - cmake-data

before_install:
   - curl -sS "https://www.mulle-kybernetik.com/dists/debian-admin-pub.asc" | sudo apt-key add -
   - echo "deb [arch=all] http://www.mulle-kybernetik.com `lsb_release -c -s` main" | sudo tee "/etc/apt/sources.list.d/mulle-kybernetik.com-main.list" > /dev/null
   - sudo apt-get update
   - sudo apt-get -y install mulle-sde

script:
   - mulle-sde -DMULLE_SDE_EXTENSION_BASE_PATH="${PWD}/src" extension list
   - mulle-sde -DMULLE_SDE_EXTENSION_BASE_PATH="${PWD}/src" init -d exe -m mulle-sde/c-developer executable
   - cd exe
   - mulle-sde craft
   - "./build/Release/exe"
   - cd ..
   - mulle-sde -DMULLE_SDE_EXTENSION_BASE_PATH="${PWD}/src" init -d lib -m mulle-sde/c-developer library
   - cd lib
   - mulle-sde -v craft
