#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


run_mulle_sde()
{
   log_fluff "####################################" >&2
   log_fluff ${MULLE_SDE} ${MULLE_SDE_FLAGS} "$@"
   log_fluff "####################################" >&2

   (
      MULLE_EXECUTABLE="${MULLE_SDE}"
      MULLE_SDE_LIBEXEC_DIR="`${MULLE_SDE} libexec-dir`"

      . "${MULLE_SDE}" --no-auto-shell ${MULLE_SDE_FLAGS} "$@"
   )
}


expect()
{
   local expected="$1"
   local filename="$2"

   local result

   result="`cat "${filename}"`"
   log_debug "${filename}: ${result}"
   if [ "${expected}" != "${result}" ]
   then
      fail "${filename}: \"${result}\" != \"${expected}\""
   fi
}


main()
{
   MULLE_SDE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   export MULLE_SDE_EXTENSION_PATH

   local directory

   r_make_tmp_directory
   directory="${RVAL:-/tmp/build}"

   #
   # this tests that the definition for CC is used by a but not by b
   #
   mulle-sde init --no-post-init -d "${directory}/b" -m mulle-sde/c-developer library || exit 1

   mulle-sde init --no-post-init -d "${directory}/a" -m mulle-sde/c-developer executable || exit 1
   (
      cd "${directory}/a" &&
      mulle-sde dependency add b &&
      mkdir bin &&
      cat <<EOF > bin/foo-cc || exit 1
#! /bin/sh -x

#
# can't use [C][C] here as cmake greps for it and then hangs
#
exec "cc" "\$@"
EOF

      chmod 755 bin/foo-cc &&
      mulle-sde environment set PATH "\${PWD}/bin:\${PATH}" &&
      mulle-sde definition set CC foo-cc &&
      mulle-sde craft
   ) || exit 1

   set -o pipefail
   (
      cd "${directory}/a" &&
      mulle-sde -s log | egrep -q foo-cc
      if [ $? -ne 0 ]
      then
         internal_fail "foo-cc was not used"
      fi

      mulle-sde -s log b | egrep -q foo-cc
      if [ $? -eq 0 ]
      then
         internal_fail "foo-cc was mistakenly used"
      fi
   )

   log_verbose "----- #1 PASSED -----"

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SDE_EXTENSION_PATH="${PWD}/../../src:${MULLE_SDE_EXTENSION_PATH}"
}

init "$@"
main "$@"

