#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###


run_mulle_sde()
{
   log_fluff "####################################"
   log_fluff mulle-sde ${MULLE_SDE_FLAGS} "$@"
   log_fluff "####################################"

   exekutor mulle-sde ${MULLE_SDE_FLAGS} "$@"
}


expect()
{
   local expected="$1"
   local filename="$2"

   local result

   result="`cat "${filename}"`"
   log_debug "${filename}: ${result}"
   if [ "${expected}" != "${result}" ]
   then
      fail "${filename}: \"${result}\" != \"${expected}\""
   fi
}


main()
{
   MULLE_SDE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   export MULLE_SDE_EXTENSION_PATH

   local directory

   r_make_tmp_directory
   directory="${RVAL:-/tmp/build}"

   #
   # this tests that the definition for CC is used by a but not by b
   #
   run_mulle_sde init --no-post-init -d "${directory}/b" -m mulle-sde/c-developer library || exit 1

   run_mulle_sde init --no-post-init -d "${directory}/a" -m mulle-sde/c-developer executable || exit 1
   (
      cd "${directory}/a" &&
      run_mulle_sde dependency add b &&
      mkdir bin &&
      cat <<EOF > bin/foo-cc || exit 1
#! /bin/sh -x

#
# can't use [C][C] here as cmake greps for it and then hangs
#
exec "cc" "\$@"
EOF

      chmod 755 bin/foo-cc &&
      run_mulle_sde environment set PATH "\${PWD}/bin:\${PATH}" &&
      run_mulle_sde definition set CC foo-cc &&
      run_mulle_sde craft
   ) || exit 1

   set -o pipefail
   (
      cd "${directory}/a" &&
      run_mulle_sde -s log | egrep -q foo-cc
      if [ $? -ne 0 ]
      then
         _internal_fail "foo-cc was not used"
      fi

      run_mulle_sde -s log b | egrep -q foo-cc
      if [ $? -eq 0 ]
      then
         _internal_fail "foo-cc was mistakenly used"
      fi
   ) || exit 1

   log_verbose "----- #1 PASSED -----"

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_SDE_EXTENSION_PATH="${PWD}/../../src:${MULLE_SDE_EXTENSION_PATH}"
}

init "$@"
main "$@"

