#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x


run_mulle_sde()
{
   log_fluff "####################################"
   log_fluff mulle-sde ${MULLE_SDE_FLAGS} "$@"
   log_fluff "####################################"

   exekutor mulle-sde ${MULLE_SDE_FLAGS} "$@"
}


_setup_test()
{
   (
      exekutor cd "$1"     &&
      exekutor mkdir repos &&

      (
         exekutor cd repos &&

         log_fluff "setup a & c" &&
         run_mulle_sde init --no-post-init -m mulle-sde/c-developer -d a library &&
         run_mulle_sde init --no-post-init -m mulle-sde/c-developer -d c library &&

         log_info "setup b with dependency c in a" &&
         (
            exekutor cd a &&
            run_mulle_sde subproject init -d b library &&
            run_mulle_sde subproject --subproject b dependency add --nodetype git c &&
            log_fluff "run update in a" &&
            run_mulle_sde update
         ) &&

         log_info "run update in c (leaf)" &&
         (
            exekutor cd c &&
            run_mulle_sde update
         )
      ) &&

      log_info "add project with dependency a" &&
      (
         run_mulle_sde init --no-post-init -m mulle-sde/c-developer -d project executable &&
         cd project &&

         run_mulle_sde environment set MULLE_FETCH_SEARCH_PATH "${PWD}/../repos" &&
         run_mulle_sde dependency add --nodetype git a
      )
   )
}


main()
{
   MULLE_SDE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory
   local dstdir
   local repo

   r_make_tmp_directory || exit 1
   directory="${RVAL}"
   _setup_test "${directory}" || fail "Test setup failed"

   cd "${directory}/project"  || fail "cd failed"
   run_mulle_sde fetch || fail "Test fetch failed"
   run_mulle_sde craft || fail "Test craft failed"

   log_verbose "----- #1 PASSED -----"

   log_info "----- ALL PASSED -----"

   # rmdir_safer "${directory}"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SDE_EXTENSION_PATH="${PWD}/../../src:${MULLE_SDE_EXTENSION_PATH}"
}


init "$@"
main "$@"

