name: CI

on: [push]

env:
  BUILD_TYPE: release
  MULLE_SDE_GITHUB_CI_VENDOR: ${{ secrets.MULLE_SDE_GITHUB_CI_VENDOR }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    # mulle-sde is default, unless we are in a Mulle* project (but not in
    # a mulle-* project)
    - uses: mulle-sde/github-ci@v1
      if: (env.MULLE_SDE_GITHUB_CI_VENDOR == '' && ! (startsWith( env.GITHUB_REPOSITORY, 'Mulle') && ! startsWith( env.GITHUB_REPOSITORY, 'mulle-'))) || env.MULLE_SDE_GITHUB_CI_VENDOR == 'mulle-sde'

    - uses: mulle-objc/github-ci@v1
      if: env.MULLE_SDE_GITHUB_CI_VENDOR == 'mulle-objc'

    # MulleFoundation is default, when we are in a Mulle* project, unless
    # we are in a mulle-* project. It's not case-sensitive :(
    - uses: MulleFoundation/github-ci@v1
      if: (env.MULLE_SDE_GITHUB_CI_VENDOR == '' && (startsWith( env.GITHUB_REPOSITORY, 'Mulle') && ! startsWith( env.GITHUB_REPOSITORY, 'mulle-'))) || env.MULLE_SDE_GITHUB_CI_VENDOR == 'MulleFoundation'

    - name: Add to path
      run:  echo "$HOME/bin" >> $GITHUB_PATH

    - name: Dump Build Environment
      run:  env

    - name: Mulle-SDE Fetch
      run: mulle-sde fetch

    - name: Mulle-SDE Craft
      run: mulle-sde craft --${BUILD_TYPE:-release}

    - name: Mulle-SDE Test
      run: mulle-sde test
